version: 2

jobs:
  build:
    docker:
      - image: circleci/node:10

    steps:
      - checkout

      - run: npm install
      - run:
          name: Starting server
          command: npm run start:dev
          background: true
      - run: sleep 10

      # This will authenticate using the `ENGINE_API_KEY` environment
      # variable. If the GraphQL server is available somewhere other than
      # http://localhost:4000/graphql, set it with `--endpoint=<URL>`.
      - run: npm run schema:check

      # When running on the 'master' branch, publish the latest version
      # of the schema to Apollo Engine.
      - run: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            npm run schema:publish
          fi
      - run:
          name: lint
          command: npm run lint

      - run:
          name: test
          command: npm test
